Move prover returns: exiting with boogie verification errors
error: function does not emit the expected event
    ┌─ tests/sources/functional/emits.move:121:9
    │
121 │         emits DummyEvent{msg: 0} to handle;
    │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    │
    =     at tests/sources/functional/emits.move:115: conditional_missing_condition_incorrect
    =         x = <redacted>
    =         handle = <redacted>
    =     at tests/sources/functional/emits.move:116: conditional_missing_condition_incorrect
    =         handle = <redacted>
    =     at tests/sources/functional/emits.move:119: conditional_missing_condition_incorrect
    =     at tests/sources/functional/emits.move:121

error: function does not emit the expected event
    ┌─ tests/sources/functional/emits.move:160:9
    │
160 │         emits DummyEvent{msg: 2} to handle;
    │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    │
    =     at tests/sources/functional/emits.move:150: conditional_multiple_incorrect
    =         b = <redacted>
    =         handle = <redacted>
    =     at tests/sources/functional/emits.move:151: conditional_multiple_incorrect
    =     at tests/sources/functional/emits.move:152: conditional_multiple_incorrect
    =     at tests/sources/functional/emits.move:153: conditional_multiple_incorrect
    =         handle = <redacted>
    =     at tests/sources/functional/emits.move:156: conditional_multiple_incorrect
    =     at tests/sources/functional/emits.move:158
    =     at tests/sources/functional/emits.move:159
    =     at tests/sources/functional/emits.move:160

error: function does not emit the expected event
    ┌─ tests/sources/functional/emits.move:190:9
    │
190 │         emits DummyEvent{msg: 0} to handle;
    │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    │
    =     at tests/sources/functional/emits.move:180: conditional_multiple_same_incorrect
    =         b = <redacted>
    =         handle = <redacted>
    =     at tests/sources/functional/emits.move:181: conditional_multiple_same_incorrect
    =     at tests/sources/functional/emits.move:182: conditional_multiple_same_incorrect
    =     at tests/sources/functional/emits.move:183: conditional_multiple_same_incorrect
    =         handle = <redacted>
    =     at tests/sources/functional/emits.move:186: conditional_multiple_same_incorrect
    =     at tests/sources/functional/emits.move:188
    =     at tests/sources/functional/emits.move:189
    =     at tests/sources/functional/emits.move:190

error: function does not emit the expected event
    ┌─ tests/sources/functional/emits.move:112:9
    │
112 │         emits DummyEvent{msg: 0} to handle if x > 0;
    │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    │
    =     at tests/sources/functional/emits.move:106: conditional_wrong_condition_incorrect
    =         x = <redacted>
    =         handle = <redacted>
    =     at tests/sources/functional/emits.move:107: conditional_wrong_condition_incorrect
    =         handle = <redacted>
    =     at tests/sources/functional/emits.move:110: conditional_wrong_condition_incorrect
    =     at tests/sources/functional/emits.move:112

error: function does not emit the expected event
   ┌─ tests/sources/functional/emits.move:55:9
   │
55 │         emits DummyEvent{msg: 2} to handle;
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   │
   =     at tests/sources/functional/emits.move:48: multiple_incorrect
   =         handle = <redacted>
   =     at tests/sources/functional/emits.move:49: multiple_incorrect
   =     at tests/sources/functional/emits.move:50: multiple_incorrect
   =         handle = <redacted>
   =     at tests/sources/functional/emits.move:51: multiple_incorrect
   =     at tests/sources/functional/emits.move:53
   =     at tests/sources/functional/emits.move:54
   =     at tests/sources/functional/emits.move:55

error: function does not emit the expected event
   ┌─ tests/sources/functional/emits.move:72:9
   │
72 │         emits DummyEvent{msg: 0} to handle;
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   │
   =     at tests/sources/functional/emits.move:67: multiple_same_incorrect
   =         handle = <redacted>
   =     at tests/sources/functional/emits.move:68: multiple_same_incorrect
   =         handle = <redacted>
   =     at tests/sources/functional/emits.move:69: multiple_same_incorrect
   =     at tests/sources/functional/emits.move:71
   =     at tests/sources/functional/emits.move:72

error: emitted event not covered by any of the `emits` clauses
    ┌─ tests/sources/functional/emits.move:315:5
    │
315 │ ╭     spec opaque_completeness_incorrect {
316 │ │         emits DummyEvent{msg: 0} to handle;
317 │ │         emits DummyEvent{msg: 7} to handle;
318 │ │         emits DummyEvent{msg: 1} to handle;
319 │ │     }
    │ ╰─────^
    │
    =     at tests/sources/functional/emits.move:310: opaque_completeness_incorrect
    =         handle = <redacted>
    =     at tests/sources/functional/emits.move:311: opaque_completeness_incorrect
    =     at tests/sources/functional/emits.move:312: opaque_completeness_incorrect
    =     at tests/sources/functional/emits.move:264: callee
    =         handle = <redacted>
    =     at tests/sources/functional/emits.move:265: callee
    =     at tests/sources/functional/emits.move:266: callee
    =         handle = <redacted>
    =     at tests/sources/functional/emits.move:267: callee
    =     at tests/sources/functional/emits.move:313: opaque_completeness_incorrect
    =         handle = <redacted>
    =     at tests/sources/functional/emits.move:314: opaque_completeness_incorrect
    =     at tests/sources/functional/emits.move:316
    =     at tests/sources/functional/emits.move:317
    =     at tests/sources/functional/emits.move:318
    =     at tests/sources/functional/emits.move:315

error: function does not emit the expected event
    ┌─ tests/sources/functional/emits.move:297:9
    │
297 │         emits DummyEvent{msg: 2} to handle;
    │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    │
    =     at tests/sources/functional/emits.move:287: opaque_incorrect
    =         handle = <redacted>
    =     at tests/sources/functional/emits.move:288: opaque_incorrect
    =     at tests/sources/functional/emits.move:289: opaque_incorrect
    =     at tests/sources/functional/emits.move:264: callee
    =         handle = <redacted>
    =     at tests/sources/functional/emits.move:265: callee
    =     at tests/sources/functional/emits.move:266: callee
    =         handle = <redacted>
    =     at tests/sources/functional/emits.move:267: callee
    =     at tests/sources/functional/emits.move:290: opaque_incorrect
    =         handle = <redacted>
    =     at tests/sources/functional/emits.move:291: opaque_incorrect
    =     at tests/sources/functional/emits.move:293
    =     at tests/sources/functional/emits.move:294
    =     at tests/sources/functional/emits.move:295
    =     at tests/sources/functional/emits.move:296
    =     at tests/sources/functional/emits.move:297

error: emitted event not covered by any of the `emits` clauses
    ┌─ tests/sources/functional/emits.move:236:5
    │
236 │ ╭     spec partial_incorrect {
237 │ │         emits DummyEvent{msg: 0} to handle;
238 │ │     }
    │ ╰─────^
    │
    =     at tests/sources/functional/emits.move:232: partial_incorrect
    =         handle = <redacted>
    =     at tests/sources/functional/emits.move:233: partial_incorrect
    =     at tests/sources/functional/emits.move:234: partial_incorrect
    =         handle = <redacted>
    =     at tests/sources/functional/emits.move:235: partial_incorrect
    =     at tests/sources/functional/emits.move:237
    =     at tests/sources/functional/emits.move:236

error: function does not emit the expected event
   ┌─ tests/sources/functional/emits.move:31:9
   │
31 │         emits DummyEvent{msg: 0} to _handle2;
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   │
   =     at tests/sources/functional/emits.move:27: simple_wrong_handle_incorrect
   =         handle = <redacted>
   =         _handle2 = <redacted>
   =     at tests/sources/functional/emits.move:28: simple_wrong_handle_incorrect
   =         handle = <redacted>
   =         _handle2 = <redacted>
   =     at tests/sources/functional/emits.move:29: simple_wrong_handle_incorrect
   =     at tests/sources/functional/emits.move:31

error: function does not emit the expected event
   ┌─ tests/sources/functional/emits.move:24:9
   │
24 │         emits DummyEvent{msg: 1} to handle;
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   │
   =     at tests/sources/functional/emits.move:20: simple_wrong_msg_incorrect
   =         handle = <redacted>
   =     at tests/sources/functional/emits.move:21: simple_wrong_msg_incorrect
   =         handle = <redacted>
   =     at tests/sources/functional/emits.move:22: simple_wrong_msg_incorrect
   =     at tests/sources/functional/emits.move:24

error: emitted event not covered by any of the `emits` clauses
    ┌─ tests/sources/functional/emits.move:256:5
    │
256 │ ╭     spec strict_incorrect {
257 │ │         pragma emits_is_strict;
258 │ │     }
    │ ╰─────^
    │
    =     at tests/sources/functional/emits.move:252: strict_incorrect
    =         handle = <redacted>
    =     at tests/sources/functional/emits.move:253: strict_incorrect
    =     at tests/sources/functional/emits.move:254: strict_incorrect
    =         handle = <redacted>
    =     at tests/sources/functional/emits.move:255: strict_incorrect
    =     at tests/sources/functional/emits.move:256
